data = {
    "publications": [
        {
            "name": "Self-supervised Learning of Dense Shape Correspondence",
            "authors": "Oshri Halimi, <strong>Or Litany</strong>, Emanuele Rodolà, Alex Bronstein, Ron Kimmel",
            "publication": "Computer Vision and Pattern Recognition (CVPR), 2019",
            "image": "./OL_files/unsupervised_fmnet.png",
            "paper": "https://arxiv.org/pdf/1812.02415.pdf",
            "bibtex": `@article{halimi2018self,
  title={Self-supervised Learning of Dense Shape Correspondence},
  author={Halimi, Oshri and Litany, Or and Rodol{\`a}, Emanuele and Bronstein, Alex and Kimmel, Ron},
  journal={arXiv preprint arXiv:1812.02415},
  year={2018}}`
        },
        {
            "name": "Deformable Shape Completion with Graph Convolutional Autoencoders",
            "authors": "<strong>Or Litany</strong>, Alex M. Bronstein, Michael M. Bronstein, Ameesh Makadia",
            "publication": "Computer Vision and Pattern Recognition (CVPR), 2018",
            "image": "./OL_files/shapeComp.png",
            "paper": "https://arxiv.org/pdf/1712.00268v1.pdf",
            "bibtex": `@article{litany2017deformable,
Author    = {Or Litany and Alex Bronstein and Michael Bronstein and Ameesh Makadia},
Title     = {Deformable Shape Completion with Graph Convolutional Autoencoders},
Journal   = {CVPR},
Year      = {2018}}`
        },
        {
            "name": "Efficient Deformable Shape Correspondence via Kernel Matching",
            "authors": "Matthias Vestner, Zorah Lähner, Amit Boyarski, <strong>Or Litany</strong>, et. al.",
            "publication": "Intl. Conference on 3D Vision (3DV), 2017",
            "image": "./OL_files/vestner-3dv17.png",
            "paper": "https://arxiv.org/pdf/1707.08991.pdf",
            "code": "https://github.com/zorah/KernelMatching",
            "bibtex": `@article{vestner2017efficient,
Author    = {Matthias Vestner and Zorah Lähner and Amit Boyarski and Or Litany and others},
Title     = {Efficient Deformable Shape Correspondence via Kernel Matching},
Journal   = {3DV},
Year      = {2017}}`
        },
        {
            "name": "Deep Functional Maps: Structured Prediction for Dense Shape Correspondence",
            "authors": "<strong>Or Litany</strong>, Tal Remez, Emanuele Rodolà, Alex M. Bronstein, Michael M. Bronstein",
            "publication": "International Conference on Computer Vision (ICCV), 2017",
            "image": "./OL_files/FMNet.png",
            "paper": "http://vision.in.tum.de/_media/spezial/bib/litany-iccv17.pdf",
            "code": "https://github.com/orlitany/DeepFunctionalMaps",
            "bibtex": `@article{litany2017fmnet,
Author    = {Or Litany and Tal Remez and Emanuele Rodol{\`a} and Alex Bronstein and Michael Bronstein},
Title     = {Deep Functional Maps: Structured Prediction for Dense Shape Correspondence},
Journal   = {ICCV},
Year      = {2017}}`
        },
        {
            "name": "Deep Class Aware Image Denoising",
            "authors": "Tal Remez, <strong>Or Litany</strong>, Raja Giryes, Alex M. Bronstein",
            "publication": "IEEE International Conference on Image Processing (ICIP), 2017",
            "image": "./OL_files/clsawrden.png",
            "paper": "https://arxiv.org/abs/1701.01698",
            "code": "https://github.com/TalRemez/deep_class_aware_denoising",
            "bibtex": `@article{remez2017classaware,
Author    = {Tal Remez and Or Litany and Raja Giryes and Alex Bronstein},
Title     = {Deep Class Aware Denoising},
Journal   = {ICIP},
Year      = {2017}}`
        },
        {
            "name": "Cloud Dictionary: Sparse Coding and Modeling for Point Clouds",
            "authors": "<strong>Or Litany</strong>*, Tal Remez*, Alex M. Bronstein (*Equal contributors)",
            "publication": "Signal Processing with Adaptive Sparse Structured Representations (SPARS), 2017",
            "image": "./OL_files/clouddict.png",
            "paper": "https://arxiv.org/pdf/1612.04956v1",
            "bibtex": `@article{litany2016cloud,
Author    = {Or Litany and Tal Remez and Tal and Alex Bronstein},
Title     = {Deep Class Aware Denoising},
Journal   = {SPARS},
Year      = {2017}}`
        },
        {
            "name": "Fully Spectral Partial Shape Matching",
            "authors": "<strong>Or Litany</strong>,  Emanuele Rodolà, Alex M. Bronstein, Michael M. Bronstein",
            "publication": "Computer Graphics Forum, Vol. 36(2), 2017",
            "image": "./OL_files/fullyspectral.png",
            "paper": "http://vision.in.tum.de/_media/spezial/bib/litany-eg17.pdf",
            "code": "https://github.com/orlitany/FSPM",
            "misc": "Presented at <em>Eurographics</em>, 2017",
            "bibtex": `@inproceedings{litany2017fully,
title={Fully spectral partial shape matching},
author={Litany, Or and Rodol{\`a}, Emanuele and Bronstein, Alex M and Bronstein, Michael M},
booktitle={Computer Graphics Forum},
volume={36},
number={2},
pages={247--258},
year={2017},
organization={Wiley Online Library}`
        },
        {
            "name": "SHREC`17: Deformable Shape Retrieval with Missing Parts",
            "authors": "Emanuele Rodolà, Luca Cosmo, <strong>Or Litany</strong>, Michael M. Bronstein, <br> Alex M. Bronstein et al.",
            "publication": "EUROGRAPHICS Workshop on 3D Object Retrieval (3DOR), 2017",
            "image": "./OL_files/shrec17.png",
            "paper": "http://vision.in.tum.de/_media/spezial/bib/shrec17partial.pdf",
            "code": "http://vision.in.tum.de/_media/spezial/bib/shrec17-baseline.zip",
            "dataset": "https://sites.google.com/view/shrec17/",
            "bibtex": `@inproceedings{rodola2017shrec,
title={SHREC\'17: Deformable shape retrieval with missing parts},
author={Rodol{\`a}, E and Cosmo, L and Litany, O and Bronstein, MM and Bronstein, AM and Audebert, N and Hamza, A Ben and Boulch, A and Castellani, U and Do, MN and others},
booktitle={Proceedings of the Eurographics Workshop on 3D Object Retrieval, Lisbon, Portugal},
pages={23--24},
year={2017}`
        },
        {
            "name": "ASIST: Automatic Semantically Invariant Scene Transformation",
            "authors": "<strong>Or Litany</strong>, Tal Remez, Daniel Freedman, Lior Shapira, Alex Bronstein, Ran Gal",
            "publication": "Computer Vision and Image Understanding (CVIU), 2017",
            "image": "./OL_files/asist.png",
            "paper": "http://arxiv.org/abs/1512.01515",
            "bibtex": `@article{litany2015asist,
title={ASIST: automatic semantically invariant scene transformation},
author={Litany, Or and Remez, Tal and Freedman, Daniel and Shapira, Lior and Bronstein, Alex and Gal, Ran},
journal={CVIU},
pages={284--299},
volume={157},
year={2017}`
        },
        {
            "name": "Non-Rigid Puzzles",
            "authors": "<strong>Or Litany</strong>, Emanuele Rodolà, Alex Bronstein, Michael Bronstein, Daniel Cremers",
            "publication": "Computer Graphics Forum, Wiley, volume 35, 2016",
            "image": "./OL_files/puzzles.png",
            "misc": "<mark>SGP Best Paper Award</mark>",
            "paper": "http://vision.in.tum.de/_media/spezial/bib/litany16.pdf",
            "code": "https://github.com/orlitany/NonRigidPuzzles",
            "bibtex": `@inproceedings{litany2016non,
title={Non-rigid puzzles},
author={Litany, Or and Rodol{\`a}, Emanuele and Bronstein, Alexander M and Bronstein, Michael M and Cremers, Daniel},
booktitle={Computer Graphics Forum},
volume={35},
number={5},
pages={135--143},
year={2016},
organization={Wiley Online Library}`
        },
        {
            "name": "A picture is worth a billion bits: Real-time image reconstruction from dense binary threshold pixels",
            "authors": "Tal Remez*, <strong>Or Litany</strong>*, Alex Bronstein (*Equal contributors)",
            "publication": "International Conference on Computational Photography (ICCP), 2016",
            "image": "./OL_files/binarycam.png",
            "paper": "https://arxiv.org/pdf/1510.04601.pdf",
            "bibtex": `@inproceedings{remez2016picture,
title={A picture is worth a billion bits: Real-time image reconstruction from dense binary threshold pixels},
author={Remez, Tal and Litany, Or and Bronstein, Alex},
booktitle={Computational Photography (ICCP), 2016 IEEE International Conference on},
pages={1--9},
year={2016},
organization={IEEE}`
        },
        {
            "name": "Image reconstruction from dense binary pixels",
            "authors": "<strong>Or Litany</strong>*, Tal Remez*, Alex Bronstein (*Equal contributors)",
            "publication": "Signal Processing with Adaptive Sparse Structured Representations (SPARS), 2015",
            "image": "./OL_files/binarycamspars.png",
            "paper": "http://arxiv.org/abs/1512.01774",
            "bibtex": `@article{litany2015image,
title={Image reconstruction from dense binary pixels},
author={Litany, Or and Remez, Tal and Bronstein, Alex},
journal={SPARS},
year={2015}`
        },
        {
            "name": "Putting the pieces together: regularized multi-shape partial matching",
            "authors": "<strong>Or Litany</strong>, Alex Bronstein, Michael Bronstein",
            "publication": "Workshop on Nonrigid Shape Analysis and Deformable Image Alignment (NORDIA), 2012",
            "image": "./OL_files/rigidpuzzles.png",
            "paper": "http://vista.eng.tau.ac.il/publications/LitBroBroNORDIA12.pdf",
            "bibtex": `@inproceedings{litany2012putting,
title={Putting the pieces together: Regularized multi-part shape matching},
author={Litany, Or and Bronstein, Alexander M and Bronstein, Michael M},
booktitle={European Conference on Computer Vision},
pages={1--11},
year={2012},
organization={Springer}`
        },
    ]
};
