data = {  
    "publications": [
        // ------------ 2021 -----------------                
        {
          "name": "DIB-R++: Learning to Predict Lighting and Material with a Hybrid Differentiable Renderer",
          "authors": "Wenzheng Chen, Joey Litalien, Jun Gao, Zian Wang, Clement Fuji Tsang, Sameh Khamis, <strong>Or Litany</strong>, Sanja Fidler",
          "publication": "NeurIPS 2021",
          "image": "./OL_files/dibrplus_teaser.png",
          "paper": "https://arxiv.org/abs/2111.00140",          
          "page": "https://nv-tlabs.github.io/DIBRPlus/",
          "bibtex":`@inproceedings{chen2021dibrpp,
      title = {{DIB-R++}: Learning to Predict Lighting and Material with a Hybrid Differentiable Renderer},
      author = {Wenzheng Chen and Joey Litalien and Jun Gao and Zian Wang and Clement Fuji Tsang and Sameh Khalis and Or Litany and Sanja Fidler},
      year = {2021},
      booktitle = {Advances in Neural Information Processing Systems (NeurIPS)}}`
      },
        {
          "name": "Mix3D: Out-of-Context Data Augmentation for 3D Scenes",
          "authors": "Alexey Nekrasov, Jonas Schult, <strong>Or Litany</strong>, Bastian Leibe, Francis Engelmann",
          "publication": "3DV 2021",
          "image": "./OL_files/mix3d_teaser.png",
          "paper": "https://arxiv.org/abs/2110.02210",          
          "page": "https://kumuji.github.io/mix3d/",
          "bibtex":`@misc{nekrasov2021mix3d,
      title={Mix3D: Out-of-Context Data Augmentation for 3D Scenes}, 
      author={Alexey Nekrasov and Jonas Schult and Or Litany and Bastian Leibe and Francis Engelmann},
      year={2021},
      eprint={2110.02210},
      archivePrefix={arXiv},
      primaryClass={cs.CV}}`
      },
        {
          "name": "StrobeNet: Category-Level Multiview Reconstruction of Articulated Objects",
          "authors": "Ge Zhang, <strong>Or Litany</strong>, Srinath Sridhar, Leonidas Guibas",
          "publication": "arXiv",
          "image": "./OL_files/strobenet.png",
          "paper": "https://arxiv.org/abs/2105.08016",          
          "page": "https://dzhange.github.io/StrobeNet/",
          "bibtex":`@misc{zhang2021strobenet,
      title={StrobeNet: Category-Level Multiview Reconstruction of Articulated Objects}, 
      author={Ge Zhang and Or Litany and Srinath Sridhar and Leonidas Guibas},
      year={2021},
      eprint={2105.08016},
      archivePrefix={arXiv},
      primaryClass={cs.CV}}`
      },
        {
          "name": "Vector Neurons: A General Framework for SO(3)-Equivariant Networks",
          "authors": "Congyue Deng, <strong>Or Litany</strong>, Yueqi Duan, Adrien Poulenard, Andrea Tagliasacchi, Leonidas Guibas",
          "publication": "ICCV 2021",
          "image": "./OL_files/VNN_teaser.png",
          "paper": "https://arxiv.org/abs/2104.12229",          
          "bibtex":`@misc{deng2021vector,
                    title={Vector Neurons: A General Framework for SO(3)-Equivariant Networks}, 
                    author={Congyue Deng and Or Litany and Yueqi Duan and Adrien Poulenard and Andrea Tagliasacchi and Leonidas Guibas},
                    year={2021},
                    eprint={2104.12229},
                    archivePrefix={arXiv},
                    primaryClass={cs.CV}}`
      },
       {
          "name": "Contrast to Divide: Self-Supervised Pre-Training for Learning with Noisy Labels",
          "authors": "Evgenii Zheltonozhskii, Chaim Baskin, Avi Mendelson, Alex M. Bronstein, <strong>Or Litany</strong>",
          "publication": "WACV 2022",
          "image": "./OL_files/C2D_teaser.png",
          "paper": "https://arxiv.org/abs/2103.13646",          
          "bibtex":`@misc{zheltonozhskii2021contrast,
              title={Contrast to Divide: Self-Supervised Pre-Training for Learning with Noisy Labels}, 
              author={Evgenii Zheltonozhskii and Chaim Baskin and Avi Mendelson and Alex M. Bronstein and Or Litany},
              year={2021},
              eprint={2103.13646},
              archivePrefix={arXiv},
              primaryClass={cs.CV}}`
      },
      {
          "name": "ReLMoGen: Integrating Reinforcement Learning and Motion Generation for Interactive Navigation",
          "authors": "Fei Xia, Chengshu Li, Roberto Martin-Martin, Alexander Toshev, <strong>Or Litany</strong>, Silvio Savarese",
          "publication": "ICRA 2021",
          "image": "./OL_files/relmogen_teaser.png",
          "paper": "https://arxiv.org/abs/2008.07792",
          "talk": "https://youtu.be/mTaJ9xQMiD0?t=2083",
          "bibtex":`@article{xia2020relmogen,
              title={ReLMoGen: Leveraging Motion Generation in Reinforcement Learning for Mobile Manipulation},
              author={Xia, Fei and Li, Chengshu and Mart{\'\i}n-Mart{\'\i}n, Roberto and Litany, Or and Toshev, Alexander and Savarese, Silvio},
              journal={arXiv preprint arXiv:2008.07792},
              year={2020}}`
      },
      {
          "name": "Weakly Supervised Learning of Rigid 3D Scene Flow",
          "authors": "Zan Gojcic, <strong>Or Litany</strong>, Andreas Wieser, Leonidas J Guibas, Tolga Birdal",
          "publication": "CVPR 2021",
          "image": "./OL_files/weakly_cvpr21.png",
          "paper": "https://arxiv.org/abs/2102.08945",
          "page": "https://3dsceneflow.github.io/",
          "bibtex":`@misc{gojcic2021weakly,
            title={Weakly Supervised Learning of Rigid 3D Scene Flow}, 
            author={Zan Gojcic and Or Litany and Andreas Wieser and Leonidas J. Guibas and Tolga Birdal},
            year={2021},
            eprint={2102.08945},
            archivePrefix={arXiv},
            primaryClass={cs.CV}}`
      },
      {
        "name": "3DIoUMatch: Leveraging IoU Prediction for Semi-Supervised 3D Object Detection",
        "authors": "He Wang*, Yezhen Cong*, <strong>Or Litany</strong>, Yue Gao, Leonidas J. Guibas",
        "publication": "CVPR 2021",
        "image": "./OL_files/3dioumatch.png",
        "paper": "https://arxiv.org/abs/2012.04355",
        "page": "https://thu17cyz.github.io/3DIoUMatch/",
        "bibtex":`@misc{wang20203dioumatch,
    title={3DIoUMatch: Leveraging IoU Prediction for Semi-Supervised 3D Object Detection},
    author={He Wang and Yezhen Cong and Or Litany and Yue Gao and Leonidas J. Guibas},
    year={2020},
    eprint={2012.04355},
    archivePrefix={arXiv},
    primaryClass={cs.CV}}`
      },
      // ------------ 2020 -----------------
      {
          "name": "Human 3D keypoints via spatial uncertainty modeling",
          "authors": "Francis Williams, <strong>Or Litany</strong>, Avneesh Sud, Kevin Swersky, Andrea Tagliasacchi",
          "publication": "arXiv 2012.10518",
          "image": "./OL_files/3d_keypoint_estimation.png",
          "paper": "https://arxiv.org/abs/2012.10518",
          "bibtex":`@misc{williams2020human,
      title={Human 3D keypoints via spatial uncertainty modeling},
      author={Francis Williams and Or Litany and Avneesh Sud and Kevin Swersky and Andrea Tagliasacchi},
      year={2020},
      eprint={2012.10518},
      archivePrefix={arXiv},
      primaryClass={cs.CV}}`
      },      
      {
          "name": "Self-Supervised Equivariant Scene Synthesis from Video",
          "authors": "Cinjon Resnick, <strong>Or Litany</strong>, Cosmas Heiß, Hugo Larochelle, Joan Bruna, Kyunghyun Cho",
          "publication": "Neurips 2020 DiffCVGP workshop",
          "image": "./OL_files/equi_render.png",
          "paper": "https://arxiv.org/abs/2011.05787v1",
          "bibtex":`@misc{resnick2021selfsupervised,
            title={Self-Supervised Equivariant Scene Synthesis from Video}, 
            author={Cinjon Resnick and Or Litany and Cosmas Heiß and Hugo Larochelle and Joan Bruna and Kyunghyun Cho},
            year={2021},
            eprint={2102.00863},
            archivePrefix={arXiv},
            primaryClass={cs.CV}}`
      },
      {
        "name": "Representation Learning Through Latent Canonicalizations",
        "authors": "<strong>Or Litany</strong>, Ari Morcos, Srinath Sridhar, Leonidas Guibas, Judy Hoffman",
        "publication": "WACV 2021",
        "image": "./OL_files/canonicalizers.png",
        "paper": "https://arxiv.org/abs/2002.11829",
        "talk":"https://youtu.be/l1Dh4vHuYQ4",
        "bibtex":`@misc{litany2020representation,
  title={Representation Learning Through Latent Canonicalizations},
  author={Or Litany and Ari Morcos and Srinath Sridhar and Leonidas Guibas and Judy Hoffman},
  year={2020},
  eprint={2002.11829},
  archivePrefix={arXiv},
  primaryClass={cs.LG}}`
    },
        {
            "name": "Continuous Geodesic Convolutions for Learning on 3D Shapes",
            "authors": "Zhangsihao Yang, <strong>Or Litany</strong>, Tolga Birdal, Srinath Sridhar, Leonidas Guibas",
            "publication": "WACV 2021",
            "image": "./OL_files/contConv.png",
            "paper": "https://arxiv.org/abs/2002.02506",
            "bibtex":`@misc{yang2020continuous,
        title={Continuous Geodesic Convolutions for Learning on 3D Shapes},
        author={Zhangsihao Yang and Or Litany and Tolga Birdal and Srinath Sridhar and Leonidas Guibas},
        year={2020},
        eprint={2002.02506},
        archivePrefix={arXiv},
        primaryClass={cs.CV}}`
        },
        {
            "name": "Object-Centric Multi-View Aggregation",
            "authors": "Shubham Tulsiani, <strong>Or Litany</strong>, Charles R. Qi, He Wang, Leonidas Guibas",
            "publication": "Arxiv 2007.10300",
            "image": "./OL_files/mva_teaser.png",
            "paper": "http://arxiv.org/abs/2007.10300",
            "bibtex":`@misc{tulsiani2020objectcentric,
    title={Object-Centric Multi-View Aggregation},
    author={Shubham Tulsiani and Or Litany and Charles R. Qi and He Wang and Leonidas J. Guibas},
    year={2020},
    eprint={2007.10300},
    archivePrefix={arXiv},
    primaryClass={cs.CV}}`
        },
      {
          "name": "PointContrast: Unsupervised Pretraining for 3D Point Cloud Understanding",
          "authors": "Saining Xie, Jiatao Gu, Demi Guo, Charles R. Qi, Leonidas Guibas, <strong>Or Litany</strong>",
          "publication": "ECCV 2020",
          "image": "./OL_files/pointContrast.png",
          "paper": "https://arxiv.org/abs/2007.10985",
          "bibtex":`@misc{xie2020pointcontrast,
    title={PointContrast: Unsupervised Pre-training for 3D Point Cloud Understanding},
    author={Saining Xie and Jiatao Gu and Demi Guo and Charles R. Qi and Leonidas J. Guibas and Or Litany},
    year={2020},
    eprint={2007.10985},
    archivePrefix={arXiv},
    primaryClass={cs.CV}}`,
          "misc": "<mark>Spotlight</mark>"
      },
      {
        "name": "Towards Precise Completion of Deformable Shape",
        "authors": "Oshri Halimi, Ido Imanuel, <strong>Or Litany</strong>, Giovanni Trappolini, Emanuele Rodolà, Leonidas Guibas, Ron Kimmel",
        "publication": "ECCV 2020",
        "image": "./OL_files/theWhole.png",
        "paper": "https://arxiv.org/abs/2001.09650",
        "bibtex":`@misc{halimi2020greater,
  title={The Whole Is Greater Than the Sum of Its Nonrigid Parts},
  author={Oshri Halimi and Ido Imanuel and Or Litany and Giovanni Trappolini and Emanuele Rodolà and Leonidas Guibas and Ron Kimmel},
  year={2020},
  eprint={2001.09650},
  archivePrefix={arXiv},
  primaryClass={cs.CV}}`
    },      
      {
          "name": "On Learning Sets of Symmetric Elements",
          "authors": "Haggai Maron, <strong>Or Litany</strong>, Gal Chechik, Ethan Fetaya",
          "publication": "ICML 2020",
          "image": "./OL_files/dss_layer.png",
          "paper": "https://arxiv.org/abs/2002.08599",
          "misc": "<mark>Outstanding Paper Award</mark>",
          "bibtex":`@misc{maron2020learning,
    title={On Learning Sets of Symmetric Elements},
    author={Haggai Maron and Or Litany and Gal Chechik and Ethan Fetaya},
    year={2020},
    eprint={2002.08599},
    archivePrefix={arXiv},
    primaryClass={cs.LG}}`
      },
      {
          "name": "ImVoteNet: Boosting 3D Object Detection in Point Clouds with Image Votes",
          "authors": "Charles R. Qi, Xinlei Chen, <strong>Or Litany</strong>, Leonidas J. Guibas",
          "publication": "CVPR 2020",
          "image": "./OL_files/imvote.png",
          "paper": "https://arxiv.org/abs/2001.10692",
          "talk": "https://www.youtube.com/watch?v=xCnbvgMAg-Y",
          "bibtex":`@misc{qi2020imvotenet,
    title={ImVoteNet: Boosting 3D Object Detection in Point Clouds with Image Votes},
    author={Charles R. Qi and Xinlei Chen and Or Litany and Leonidas J. Guibas},
    year={2020},
    eprint={2001.10692},
    archivePrefix={arXiv},
    primaryClass={cs.CV}}`
      },
  // ------------ 2019 -----------------
      {
          "name": "Deep Hough Voting for 3D Object Detection in Point Clouds",
          "authors": "Charles R. Qi, <strong>Or Litany</strong>, Kaiming He, Leonidas J. Guibas",
          "publication": "International Conference on Computer Vision (ICCV), 2019",
          "image": "./OL_files/DHV_teaser.png",
          "paper": "https://arxiv.org/pdf/1904.09664.pdf",
          "code": "https://github.com/facebookresearch/votenet",
          "slides": "./OL_files/talks/deep_hough_voting.pdf",
          "talk": "https://youtu.be/2ntDYowHbZs?t=4585",
          "misc": "<mark>Best Paper Nomination</mark>",
          "bibtex":`@article{qi2019deep,
  title={Deep Hough Voting for 3D Object Detection in Point Clouds},
  author={Qi, Charles R and Litany, Or and He, Kaiming and Guibas, Leonidas J},
  journal={arXiv preprint arXiv:1904.09664},
  year={2019}}`
      },
      {
          "name": "Dual-primal graph convolutional networks",
          "authors": "Federico Monti, Oleksandr Shchur, Aleksandar Bojchevski, <strong>Or Litany</strong>, Stephan Günnemann, Michael M Bronstein",
          "publication": "GEM workshop at ECML-PKDD, 2019",
          "misc": "<mark>Oral presentation</mark>",
          "image": "./OL_files/dualprimal.png",
          "paper": "https://arxiv.org/pdf/1806.00770.pdf",
          "bibtex": `@article{monti2018dual,
title={Dual-primal graph convolutional networks},
author={Monti, Federico and Shchur, Oleksandr and Bojchevski, Aleksandar and Litany, Or and G{\"u}nnemann, Stephan and Bronstein, Michael M},
journal={arXiv preprint arXiv:1806.00770},
year={2018}}`
      },
        {
            "name": "SOSELETO: A Unified Approach to Transfer Learning and Training with Noisy Labels",
            "authors": "<strong>Or Litany</strong>, Daniel Freedman",
            "publication": "ICLR workshop on Learning from Limited Labeled Data, 2019",
            "misc": "<mark>Best Paper Award</mark>",
            "image": "./OL_files/soseleto.png",
            "paper": "https://arxiv.org/pdf/1805.09622.pdf",
            "code": "https://github.com/orlitany/SOSELETO",
            "poster": "./OL_files/SOSELETO_ICLR19_poster.pdf",
            "slides": "./OL_files/SOSELETO_presentation.pdf",
            "talk": "https://slideslive.com/38915746",
            "bibtex": `@article{litany2018soseleto,
  Author    = {Or Litany and Daniel Freedman},
  Title     = {SOSELETO: A Unified Approach to Transfer Learning and Training with Noisy Labels},
  Journal   = {arXiv preprint arXiv:1805.09622},
  Year      = {2018}}`
        },
        {
            "name": "Self-supervised Learning of Dense Shape Correspondence",
            "authors": "Oshri Halimi, <strong>Or Litany</strong>, Emanuele Rodolà, Alex Bronstein, Ron Kimmel",
            "publication": "Computer Vision and Pattern Recognition (CVPR), 2019",
            "image": "./OL_files/unsupervised_fmnet.png",
            "paper": "https://arxiv.org/pdf/1812.02415.pdf",
            "misc": "<mark>Oral presentation</mark>",
            "code": "https://github.com/OshriHalimi/unsupervised_learning_of_dense_shape_correspondence",
            "talk": "https://www.linkedin.com/feed/update/urn:li:activity:6547910607310598144",
            "bibtex": `@article{halimi2018self,
  title={Self-supervised Learning of Dense Shape Correspondence},
  author={Halimi, Oshri and Litany, Or and Rodol{\`a}, Emanuele and Bronstein, Alex and Kimmel, Ron},
  journal={arXiv preprint arXiv:1812.02415},
  year={2018}}`
        },
  // ------------ 2018 -----------------
        {
            "name": "Deformable Shape Completion with Graph Convolutional Autoencoders",
            "authors": "<strong>Or Litany</strong>, Alex M. Bronstein, Michael M. Bronstein, Ameesh Makadia",
            "publication": "Computer Vision and Pattern Recognition (CVPR), 2018",
            "image": "./OL_files/shapeComp.png",
            "paper": "https://arxiv.org/pdf/1712.00268v1.pdf",
            "bibtex": `@article{litany2017deformable,
Author    = {Or Litany and Alex Bronstein and Michael Bronstein and Ameesh Makadia},
Title     = {Deformable Shape Completion with Graph Convolutional Autoencoders},
Journal   = {CVPR},
Year      = {2018}}`
        },
        {
            "name": "Partial Single-and Multishape Dense Correspondence Using Functional Maps",
            "authors": "<strong>Or Litany</strong>, Emanuele Rodolà, Alex Bronstein, Michael Bronstein, Daniel Cremers",
            "publication": "Handbook of Numerical Analysis, Elsevier, 2018",
            "image": "./OL_files/pfm_book.png",
            "paper": "https://www.sciencedirect.com/science/article/pii/S1570865918300097",
            "bibtex": `@article{litany2018partial,
title={Partial Single-and Multishape Dense Correspondence Using Functional Maps},
author={Litany, Or and Rodol{\`a}, Emanuele and Bronstein, Alex and Bronstein, Michael and Cremers, Daniel},
year={2018},
publisher={Elsevier}}`
        },
        {
            "name": "Class-Aware Fully Convolutional Gaussian and Poisson Denoising",
            "authors": "Tal Remez, <strong>Or Litany</strong>, Raja Giryes, Alex M. Bronstein",
            "publication": "IEEE Transactions on Image Processing, 2018",
            "image": "./OL_files/class_aware_poiss.png",
            "paper": "https://arxiv.org/pdf/1808.06562.pdf",
            "code": "https://github.com/TalRemez/deep_class_aware_denoising",
            "bibtex": `@article{remez2018class,
title={Class-Aware Fully Convolutional Gaussian and Poisson Denoising},
author={Remez, Tal and Litany, Or and Giryes, Raja and Bronstein, Alex M},
journal={IEEE Transactions on Image Processing},
volume={27},
number={11},
pages={5707--5722},
year={2018},
publisher={IEEE}}`
        },


  // ------------ 2017 -----------------
        {
            "name": "Efficient Deformable Shape Correspondence via Kernel Matching",
            "authors": "Matthias Vestner, Zorah Lähner, Amit Boyarski, <strong>Or Litany</strong>, et. al.",
            "publication": "Intl. Conference on 3D Vision (3DV), 2017",
            "image": "./OL_files/vestner-3dv17.png",
            "paper": "https://arxiv.org/pdf/1707.08991.pdf",
            "code": "https://github.com/zorah/KernelMatching",
            "bibtex": `@article{vestner2017efficient,
Author    = {Matthias Vestner and Zorah Lähner and Amit Boyarski and Or Litany and others},
Title     = {Efficient Deformable Shape Correspondence via Kernel Matching},
Journal   = {3DV},
Year      = {2017}}`
        },
        {
            "name": "Deep Functional Maps: Structured Prediction for Dense Shape Correspondence",
            "authors": "<strong>Or Litany</strong>, Tal Remez, Emanuele Rodolà, Alex M. Bronstein, Michael M. Bronstein",
            "publication": "International Conference on Computer Vision (ICCV), 2017",
            "image": "./OL_files/FMNet.png",
            "paper": "http://vision.in.tum.de/_media/spezial/bib/litany-iccv17.pdf",
            "code": "https://github.com/orlitany/DeepFunctionalMaps",
            "bibtex": `@article{litany2017fmnet,
Author    = {Or Litany and Tal Remez and Emanuele Rodol{\`a} and Alex Bronstein and Michael Bronstein},
Title     = {Deep Functional Maps: Structured Prediction for Dense Shape Correspondence},
Journal   = {ICCV},
Year      = {2017}}`
        },
        {
            "name": "Deep Class Aware Image Denoising",
            "authors": "Tal Remez, <strong>Or Litany</strong>, Raja Giryes, Alex M. Bronstein",
            "publication": "IEEE International Conference on Image Processing (ICIP), 2017",
            "image": "./OL_files/clsawrden.png",
            "paper": "https://arxiv.org/abs/1701.01698",
            "code": "https://github.com/TalRemez/deep_class_aware_denoising",
            "bibtex": `@article{remez2017classaware,
Author    = {Tal Remez and Or Litany and Raja Giryes and Alex Bronstein},
Title     = {Deep Class Aware Denoising},
Journal   = {ICIP},
Year      = {2017}}`
        },
        {
            "name": "Cloud Dictionary: Sparse Coding and Modeling for Point Clouds",
            "authors": "<strong>Or Litany</strong>*, Tal Remez*, Alex M. Bronstein (*Equal contributors)",
            "publication": "Signal Processing with Adaptive Sparse Structured Representations (SPARS), 2017",
            "image": "./OL_files/clouddict.png",
            "paper": "https://arxiv.org/pdf/1612.04956v1",
            "bibtex": `@article{litany2016cloud,
Author    = {Or Litany and Tal Remez and Tal and Alex Bronstein},
Title     = {Cloud Dictionary: Sparse Coding and Modeling for Point Clouds},
Journal   = {SPARS},
Year      = {2017}}`
        },
        {
            "name": "Fully Spectral Partial Shape Matching",
            "authors": "<strong>Or Litany</strong>,  Emanuele Rodolà, Alex M. Bronstein, Michael M. Bronstein",
            "publication": "Computer Graphics Forum, Vol. 36(2), 2017",
            "image": "./OL_files/fullyspectral.png",
            "paper": "http://vision.in.tum.de/_media/spezial/bib/litany-eg17.pdf",
            "code": "https://github.com/orlitany/FSPM",
            "misc": "Presented at <em>Eurographics</em>, 2017",
            "bibtex": `@inproceedings{litany2017fully,
title={Fully spectral partial shape matching},
author={Litany, Or and Rodol{\`a}, Emanuele and Bronstein, Alex M and Bronstein, Michael M},
booktitle={Computer Graphics Forum},
volume={36},
number={2},
pages={247--258},
year={2017},
organization={Wiley Online Library}`
        },
        {
            "name": "SHREC`17: Deformable Shape Retrieval with Missing Parts",
            "authors": "Emanuele Rodolà, Luca Cosmo, <strong>Or Litany</strong>, Michael M. Bronstein, <br> Alex M. Bronstein et al.",
            "publication": "EUROGRAPHICS Workshop on 3D Object Retrieval (3DOR), 2017",
            "image": "./OL_files/shrec17.png",
            "paper": "http://vision.in.tum.de/_media/spezial/bib/shrec17partial.pdf",
            "code": "http://vision.in.tum.de/_media/spezial/bib/shrec17-baseline.zip",
            "dataset": "https://sites.google.com/view/shrec17/",
            "bibtex": `@inproceedings{rodola2017shrec,
title={SHREC\'17: Deformable shape retrieval with missing parts},
author={Rodol{\`a}, E and Cosmo, L and Litany, O and Bronstein, MM and Bronstein, AM and Audebert, N and Hamza, A Ben and Boulch, A and Castellani, U and Do, MN and others},
booktitle={Proceedings of the Eurographics Workshop on 3D Object Retrieval, Lisbon, Portugal},
pages={23--24},
year={2017}`
        },
        {
            "name": "ASIST: Automatic Semantically Invariant Scene Transformation",
            "authors": "<strong>Or Litany</strong>, Tal Remez, Daniel Freedman, Lior Shapira, Alex Bronstein, Ran Gal",
            "publication": "Computer Vision and Image Understanding (CVIU), 2017",
            "image": "./OL_files/asist.png",
            "paper": "http://arxiv.org/abs/1512.01515",
            "bibtex": `@article{litany2015asist,
title={ASIST: automatic semantically invariant scene transformation},
author={Litany, Or and Remez, Tal and Freedman, Daniel and Shapira, Lior and Bronstein, Alex and Gal, Ran},
journal={CVIU},
pages={284--299},
volume={157},
year={2017}`
        },
    // ------------ 2016 -----------------
        {
            "name": "Non-Rigid Puzzles",
            "authors": "<strong>Or Litany</strong>, Emanuele Rodolà, Alex Bronstein, Michael Bronstein, Daniel Cremers",
            "publication": "Computer Graphics Forum, Wiley, volume 35, 2016",
            "image": "./OL_files/puzzles.png",
            "misc": "<mark>SGP Best Paper Award</mark>",
            "paper": "http://vision.in.tum.de/_media/spezial/bib/litany16.pdf",
            "code": "https://github.com/orlitany/NonRigidPuzzles",
            "bibtex": `@inproceedings{litany2016non,
title={Non-rigid puzzles},
author={Litany, Or and Rodol{\`a}, Emanuele and Bronstein, Alexander M and Bronstein, Michael M and Cremers, Daniel},
booktitle={Computer Graphics Forum},
volume={35},
number={5},
pages={135--143},
year={2016},
organization={Wiley Online Library}`
        },
        {
            "name": "A picture is worth a billion bits: Real-time image reconstruction from dense binary threshold pixels",
            "authors": "Tal Remez*, <strong>Or Litany</strong>*, Alex Bronstein (*Equal contributors)",
            "publication": "International Conference on Computational Photography (ICCP), 2016",
            "image": "./OL_files/binarycam.png",
            "paper": "https://arxiv.org/pdf/1510.04601.pdf",
            "bibtex": `@inproceedings{remez2016picture,
title={A picture is worth a billion bits: Real-time image reconstruction from dense binary threshold pixels},
author={Remez, Tal and Litany, Or and Bronstein, Alex},
booktitle={Computational Photography (ICCP), 2016 IEEE International Conference on},
pages={1--9},
year={2016},
organization={IEEE}`
        },
        {
            "name": "FPGA system for real-time computational extended depth of field imaging using phase aperture coding",
            "authors": "Tal Remez, <strong>Or Litany</strong>, Shachar Yoseff, Harel Haim, Alex Bronstein",
            "publication": "arXiv preprint, 2016",
            "image": "./OL_files/fpga.png",
            "paper": "https://arxiv.org/abs/1608.01074",
            "bibtex": `@article{remez2016fpga,
      title={FPGA system for real-time computational extended depth of field imaging <br> using phase aperture coding},
      author={Remez, Tal and Litany, Or and Yoseff, Shachar and Haim, Harel and Bronstein, Alex},
      journal={arXiv preprint arXiv:1608.01074},
      year={2016}`
        },
    // ------------ 2015 -----------------
        {
            "name": "Image reconstruction from dense binary pixels",
            "authors": "<strong>Or Litany</strong>*, Tal Remez*, Alex Bronstein (*Equal contributors)",
            "publication": "Signal Processing with Adaptive Sparse Structured Representations (SPARS), 2015",
            "image": "./OL_files/binarycamspars.png",
            "paper": "http://arxiv.org/abs/1512.01774",
            "bibtex": `@article{litany2015image,
title={Image reconstruction from dense binary pixels},
author={Litany, Or and Remez, Tal and Bronstein, Alex},
journal={SPARS},
year={2015}`
        },
    // ------------ 2012 -----------------
        {
            "name": "Putting the pieces together: regularized multi-shape partial matching",
            "authors": "<strong>Or Litany</strong>, Alex Bronstein, Michael Bronstein",
            "publication": "Workshop on Nonrigid Shape Analysis and Deformable Image Alignment (NORDIA), 2012",
            "image": "./OL_files/rigidpuzzles.png",
            "paper": "https://vista.cs.technion.ac.il/wp-content/uploads/2018/10/LitBroBroNORDIA12.pdf",
            "bibtex": `@inproceedings{litany2012putting,
title={Putting the pieces together: Regularized multi-part shape matching},
author={Litany, Or and Bronstein, Alexander M and Bronstein, Michael M},
booktitle={European Conference on Computer Vision},
pages={1--11},
year={2012},
organization={Springer}`
        },
    ]
};
